version: "3.8"

services:
  coworking_service:
    build: .
    container_name: coworking_service
    restart: always
    ports:
      - "8081:8081"
      - "50051:50051"   # gRPC port
    depends_on:
      - coworking_db
    environment:
      DB_HOST: coworking_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: coworking_service
      DB_PORT: 5432

  coworking_db:
    image: postgres:latest
    container_name: coworking_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coworking_service
    ports:
      - "5432:5432"
    volumes:
      - coworking_data:/var/lib/postgresql/data

volumes:
  coworking_data:
