version: "3.8"

services:
  reservation_service:
    build: .
    container_name: reservation_service
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - reservation_db
    environment:
      DB_HOST: reservation_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: reservation_service
      DB_PORT: 5432

  reservation_db:
    image: postgres:latest
    container_name: reservation_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservation_service
    ports:
      - "5433:5432"
    volumes:
      - reservation_data:/var/lib/postgresql/data

volumes:
  reservation_data: