spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/twofactor
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      default-receive-queue: registration_queue

  mail:
    host: smtp.gmail.com
    port: 587
    username: 2018nightmare19@gmail.com
    password: "bnqh ksrp sdgx fyas"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    protocol: smtp

  jackson:
    serialization:
      indent-output: true



logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.amqp: DEBUG
    com.example.logger.messaging: DEBUG
