version: "3.8"

services:
  coworking_service:
    build:
      context: .
      dockerfile: coworking-service/Dockerfile
    container_name: coworking_service
    ports:
      - "8081:8081"
      - "50051:50051"
    environment:
      DB_HOST: coworking_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: coworking_service
      DB_PORT: 5432
    volumes:
      - ./proto:/proto
    depends_on:
      - coworking_db

  reservation_service:
    build:
      context: .
      dockerfile: reservation-service/Dockerfile
    container_name: reservation_service
    ports:
      - "8082:8082"
    environment:
      DB_HOST: reservation_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: reservation_service
      DB_PORT: 5432
    depends_on:
      - reservation_db
      - coworking_service

  coworking_db:
    image: postgres:latest
    container_name: coworking_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coworking_service
    ports:
      - "5433:5432"
    volumes:
      - coworking_db_data:/var/lib/postgresql/data

  reservation_db:
    image: postgres:latest
    container_name: reservation_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservation_service
    ports:
      - "5434:5432"
    volumes:
      - reservation_db_data:/var/lib/postgresql/data

volumes:
  coworking_db_data:
  reservation_db_data:
