// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: coworking_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomRequest) Reset() {
	*x = GetRoomRequest{}
	mi := &file_coworking_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRequest) ProtoMessage() {}

func (x *GetRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coworking_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return file_coworking_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetRoomRequest) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type GetRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Capacity      int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	PricePerHour  float64                `protobuf:"fixed64,5,opt,name=price_per_hour,json=pricePerHour,proto3" json:"price_per_hour,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomResponse) Reset() {
	*x = GetRoomResponse{}
	mi := &file_coworking_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomResponse) ProtoMessage() {}

func (x *GetRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coworking_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomResponse.ProtoReflect.Descriptor instead.
func (*GetRoomResponse) Descriptor() ([]byte, []int) {
	return file_coworking_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetRoomResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetRoomResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRoomResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetRoomResponse) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *GetRoomResponse) GetPricePerHour() float64 {
	if x != nil {
		return x.PricePerHour
	}
	return 0
}

func (x *GetRoomResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetSeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        uint32                 `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatRequest) Reset() {
	*x = GetSeatRequest{}
	mi := &file_coworking_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatRequest) ProtoMessage() {}

func (x *GetSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coworking_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatRequest.ProtoReflect.Descriptor instead.
func (*GetSeatRequest) Descriptor() ([]byte, []int) {
	return file_coworking_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetSeatRequest) GetSeatId() uint32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

type GetSeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	PricePerHour  float64                `protobuf:"fixed64,3,opt,name=price_per_hour,json=pricePerHour,proto3" json:"price_per_hour,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatResponse) Reset() {
	*x = GetSeatResponse{}
	mi := &file_coworking_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatResponse) ProtoMessage() {}

func (x *GetSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coworking_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatResponse.ProtoReflect.Descriptor instead.
func (*GetSeatResponse) Descriptor() ([]byte, []int) {
	return file_coworking_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetSeatResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetSeatResponse) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *GetSeatResponse) GetPricePerHour() float64 {
	if x != nil {
		return x.PricePerHour
	}
	return 0
}

func (x *GetSeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_coworking_service_proto protoreflect.FileDescriptor

const file_coworking_service_proto_rawDesc = "" +
	"\n" +
	"\x17coworking_service.proto\x12\tcoworking\")\n" +
	"\x0eGetRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\"\xa3\x01\n" +
	"\x0fGetRoomResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\x12$\n" +
	"\x0eprice_per_hour\x18\x05 \x01(\x01R\fpricePerHour\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\")\n" +
	"\x0eGetSeatRequest\x12\x17\n" +
	"\aseat_id\x18\x01 \x01(\rR\x06seatId\"w\n" +
	"\x0fGetSeatResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12$\n" +
	"\x0eprice_per_hour\x18\x03 \x01(\x01R\fpricePerHour\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2\x9e\x01\n" +
	"\x10CoworkingService\x12D\n" +
	"\vGetRoomByID\x12\x19.coworking.GetRoomRequest\x1a\x1a.coworking.GetRoomResponse\x12D\n" +
	"\vGetSeatByID\x12\x19.coworking.GetSeatRequest\x1a\x1a.coworking.GetSeatResponseB+Z)coworking-diploma/coworking-service/protob\x06proto3"

var (
	file_coworking_service_proto_rawDescOnce sync.Once
	file_coworking_service_proto_rawDescData []byte
)

func file_coworking_service_proto_rawDescGZIP() []byte {
	file_coworking_service_proto_rawDescOnce.Do(func() {
		file_coworking_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coworking_service_proto_rawDesc), len(file_coworking_service_proto_rawDesc)))
	})
	return file_coworking_service_proto_rawDescData
}

var file_coworking_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_coworking_service_proto_goTypes = []any{
	(*GetRoomRequest)(nil),  // 0: coworking.GetRoomRequest
	(*GetRoomResponse)(nil), // 1: coworking.GetRoomResponse
	(*GetSeatRequest)(nil),  // 2: coworking.GetSeatRequest
	(*GetSeatResponse)(nil), // 3: coworking.GetSeatResponse
}
var file_coworking_service_proto_depIdxs = []int32{
	0, // 0: coworking.CoworkingService.GetRoomByID:input_type -> coworking.GetRoomRequest
	2, // 1: coworking.CoworkingService.GetSeatByID:input_type -> coworking.GetSeatRequest
	1, // 2: coworking.CoworkingService.GetRoomByID:output_type -> coworking.GetRoomResponse
	3, // 3: coworking.CoworkingService.GetSeatByID:output_type -> coworking.GetSeatResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_coworking_service_proto_init() }
func file_coworking_service_proto_init() {
	if File_coworking_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coworking_service_proto_rawDesc), len(file_coworking_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coworking_service_proto_goTypes,
		DependencyIndexes: file_coworking_service_proto_depIdxs,
		MessageInfos:      file_coworking_service_proto_msgTypes,
	}.Build()
	File_coworking_service_proto = out.File
	file_coworking_service_proto_goTypes = nil
	file_coworking_service_proto_depIdxs = nil
}
